### PR TITLE
NFT1-Group addition

### PR DESCRIPTION
**Pull request by vivansis**
Testing my first NFT

### CODE REVIEW

**Comment by vivansis** [comment]
I'm not sure how to "resolve" this conflict, if needed, I only changed the group token ID and url link on the json file, and tried to do another pull request to get it added, can you help? Thanks

**Comment by vivansis** [comment]
Not sure if I did that right, but it should now be "2c72a84e73e986806779c79d2e80dfd7e713cb54789f31d1aeac188ec8e732b8": "http://cactuscoins.art"

**Comment by blockparty-sh** [comment]
Hi it looks like these are in iframes but https://cactuscoins.vivansis.com/ works - thanks.

**Comment by vivansis** [comment]
Thanks, and does this mean that now if I create any more children under this group/parent, the explorer will automatically index any images titled as the token ID?

**Pull request merged**
