### PR TITLE
Update group_icon_repos.json

### PR DESCRIPTION
**Pull request by rboydwl93**
trying to add a token.

### CODE REVIEW

**Comment by rboydwl93** [comment]
This isnt spam.  i own this token.  please let me know if i didnt do this correctly.   just trying to add a token so the nft image files display correctly.  thanks for the great work!
- rboydwl93

**Comment by blockparty-sh** [comment]
Hi! You need to add images into the corresponding folder on the github repo, it looks empty now. Please reopen when those are added. Thanks.

**Comment by rboydwl93** [comment]
> 
> 
> Hi! You need to add images into the corresponding folder on the github repo, it looks empty now. Please reopen when those are added. Thanks.

hello.  I have not make the child nft yet.  only parent.  i think i need to get parent token added first before i make the children?

**Comment by rboydwl93** [comment]
> 
> 
> > Hi! You need to add images into the corresponding folder on the github repo, it looks empty now. Please reopen when those are added. Thanks.
> 
> hello. I have not make the child nft yet. only parent. i think i need to get parent token added first before i make the children?

there would not be a need for 
image for parent

**Pull request closed without merging**
