### PR TITLE
give the commit

### PR DESCRIPTION
**Pull request by Bien25**
give the commit

### CODE REVIEW

**Comment by blockparty-sh** [comment]
Hi. ipfs.io is too unreliable and slow to use as an icon repo. You can use github pages for this pages.github.com

See this repo as an example

https://github.com/BitcoinCashNFT/bitcoincashnft.github.io

Please reopen when fixed. Thanks.

**Comment by Bien25** [comment]
Hello,

Thank you for reminding me. will do it now. thank you again.

regards,

Bien

**Comment by Bien25** [comment]
Hello Jt,

I already replace my repo from Ipfs to github.

Thank you very much

Regards,

Bien

**Comment by Bien25** [comment]
Hello Jt,

I just have a few questions,

Do I need to update the group_repos_icon of slp-explorer if I make any
changes or I added more Icons to my repo?

thank you for your help.

regards,

Bien

**Pull request closed without merging**
