### PR TITLE
Added verified status and image repo

### PR DESCRIPTION
**Pull request by shadowkite**
Hello!
I'd like to get my token verified. I'm planning to release some artwork, it would be so cool to sell them on Juungle,  or wherever :) Here's a PR and a signed message from the token minting address.  Hope this is enough, let me know otherwise!

---
Address: bitcoincash:qzpsrgd8srgmt43ern4kdtplsss0jxerhqlzpzgca6
Signature: Hwsk1fU4YQ9oDlTA3aOVv76jcxq1SBs6PopRh217aiqGHlEI2MmdDUJkc2sjcGA+AS60cF7/wbO+AFacwK0MAaA=

### CODE REVIEW

**Comment by blockparty-sh** [comment]
Hi! I opened issue here https://github.com/shadowkite/shadowkite.github.io/issues/1. This part is fine, but we expect images to be .png - thanks - just ping me when it's updated.

**Comment by shadowkite** [comment]
Ping @blockparty-sh !

**Comment by shadowkite** [comment]
Update: merged latest changes

**Comment by blockparty-sh** [comment]
Hey sorry for delay on this - it got lost in my messages.

**Pull request merged**
