### PR TITLE
fixing route

### PR DESCRIPTION
**Pull request by NavoneJuan**

### CODE REVIEW

**Comment by blockparty-sh** [comment]
Hey. If I do this with https://navonejuan.github.io it works, except it looks like /original folder is /Original instead so I'm getting 404. Could you update the navonejuan.github.io by renaming that folder and reopen this when done, I'll merge then it should work. 

For example - https://navonejuan.github.io/original/fd50dcef9f4dd208ab9a0ceac5c8656fbe5bb4957b39da73cc115e737eac1448.png should result in image.

Thanks

**Comment by NavoneJuan** [comment]
edited... many thanks
I must do the fork again?

**Comment by NavoneJuan** [comment]
It passed much time, and don't know if you see my corrections or if I do something wrong... or maybe you have many fork to do, sorry if I annoying you

**Comment by blockparty-sh** [comment]
Oh sorry this wasn't reopened so I missed it. This works now I'll merge, thanks!

**Comment by NavoneJuan** [comment]
Oh, my God!!
I am very excited ... my project is beginning to take shape ... thank you very much for your predisposition and patience

**Pull request closed without merging**
