### PR TITLE
add the hosting for my nft

### PR DESCRIPTION
**Pull request by semirhadzibulic**
hi,
pull request to add the hosting for my nft. 
hope you have a nice day!

### CODE REVIEW

**Comment by blockparty-sh** [comment]
hi! it doesnt look like your github pages is set up correctly yet. https://semirhadzibulic.github.io/nft/original/fa6aee07c918d6ebc8e8bfd2b6ac3b58d543067db8909dbc9c1df1ddf032f831.png is 404. thanks.

**Comment by semirhadzibulic** [comment]
Hi, it's not a png: https://semirhadzibulic.github.io/nft/original/fa6aee07c918d6ebc8e8bfd2b6ac3b58d543067db8909dbc9c1df1ddf032f831.gif 
Is that a problem?

**Comment by blockparty-sh** [comment]
Yes this currently works with just png. You can reopen if you add png. explorer does not support gif yet.

**Comment by semirhadzibulic** [comment]
hi,
but to merge the parent token has nothing to do with the child token, right?
when merged i can add png's to child tokens whenever i want, why do i need to have a png uploaded now, to merge my parent token?
Do i miss something? Ping @blockparty-sh

**Pull request closed without merging**
