### PR TITLE
Please add my NFT

### PR DESCRIPTION
**Pull request by bluechoco**
Please add my NFT

### CODE REVIEW

**Comment by RomitRadical** [comment]
Your github repo format is incorrect, you need to add the icons/images in folder named - "original"

**Comment by bluechoco** [comment]
> o format is incorrect, you need to add the icons/images in folder named - "original"

**Comment by bluechoco** [comment]
Hi, I put the the png file in below folder. Isn't it correct?
XAart/original/

**Comment by bluechoco** [comment]
> Your github repo format is incorrect, you need to add the icons/images in folder named - "original"

I put the image in "original" folder as below link:
XAart/original/a12b61894ea8877775b976d82ec5cc66fae31b693c2d929a80369ded485e04a1.png
Is it correct?

**Pull request merged**
