### PR TITLE
Verify NUSHARE (NUSH) token Update public/verified_tokens.json

### PR DESCRIPTION
**Pull request by nuel0023**
I have added token id get verified NUSHARE (NUSH) Token, and let me know the step to prove the ownership.

Token ID:
b7127683060534d1ab1fa68d24bac3ae1eaac2519dd0d3f016d3e48a293e136e

Website URL (optional): https://nusshare.blogspot.com/

Name of Crypto asset: (NUSHARE)
Ticker: (NUSH)
USD: 0,0000000192689
BCH: 0.000000000028552605

Token minted: 500,000,000

Token supply: 499,992,294.9599996

Runs on: BCH (Bitcoin Cash)

Listed on: Memo.cash, CCTip.io

Decimals: 8

DocumentUri: https://nusshare.blogspot.com/

Contact: @nushareal on Telegram for proof of ownership of token

Thank you

### CODE REVIEW

**Comment by nuel0023** [comment]
I have added token id get verified NUSHARE (NUSH) Token, and let me know the step to prove the ownership.

Token ID:
b7127683060534d1ab1fa68d24bac3ae1eaac2519dd0d3f016d3e48a293e136e

Website URL (optional): https://nusshare.blogspot.com/

Name of Crypto asset: (NUSHARE)
Ticker: (NUSH)
USD: 0,0000000192689
BCH: 0.000000000028552605

Token minted: 500,000,000

Token supply: 499,992,294.9599996

Runs on: BCH (Bitcoin Cash)

Listed on: Memo.cash, CCTip.io

Decimals: 8

DocumentUri: https://nusshare.blogspot.com/

Contact: @nushareal on Telegram for proof of ownership of token

Thank you

**Comment by blockparty-sh** [comment]
Hi! Some issue with making this deleted all file. Don't worry, I just added it to verified list here 2dc2b9732d244c068ab89a8fe474d245b7b42e3e - thanks.

**Comment by nuel0023** [comment]
Thanks for the help and support from the SLP/BCH team.
Best of luck to the SLP/BCH team

**Comment by nuel0023** [comment]
Hello Team

Thank you for being merged & the NUSHARE (NUSH) token has also been verified (https://simpleledger.info/token/b7127683060534d1ab1fa68d24bac3ae1eaac2519dd0d3f016d3e48a293e136e).

But the NUSHARE token logo (NUSH) is only visible on simpleledger.info while on Exchange and Wallet the Logo is not visible if there is an error, please help.

Thank you
qq1
qqq

**Pull request closed without merging**
