### PR TITLE
TKMK group token

### PR DESCRIPTION
**Pull request by content-slp-images**
Previous PR #172 

Changes: images added

### CODE REVIEW

**Comment by blockparty-sh** [comment]
Hi! It looks like one of these files was grabbed from http://usefuljs.net/fractals/docs/julia_mandelbrot.html

Do you own this site?

**Comment by content-slp-images** [comment]
It's generated by the mentioned formula in the document

**Comment by content-slp-images** [comment]
The whole idea is to generate bookmarks to sites. So the images in the `original/` folder - I don't need them, they belong to the site - image URI will point there. I need just the thumbnails - 32x32.. etc. to be visible in the explorer.

**Comment by blockparty-sh** [comment]
I don't think we can be hosting or linking to images which could cause potential copyright complaint issues, regardless of how large or small they are, sorry.

**Pull request closed without merging**
